kind: Service
apiVersion: v1
metadata:
  name: docker-kubernetes
spec:
  selector:
    app: docker-kubernetes
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  externalIPs:
  - 192.168.99.100
